python -m pip install attrs==19.3.0
python -m pip install Click==7.0
python -m pip install colorama==0.4.1
python -m pip install fastdtw==0.3.4
python -m pip install filelock==3.0.12
python -m pip install Flask==1.1.1
python -m pip install Flask-SocketIO==4.2.1
python -m pip install funcsigs==1.0.2
python -m pip install importlib-metadata==1.1.0
python -m pip install itsdangerous==1.1.0
python -m pip install Jinja2==2.10.3
python -m pip install jsonschema==3.2.0
python -m pip install MarkupSafe==1.1.1
python -m pip install more-itertools==8.0.0
python -m pip install numpy==1.17.4
python -m pip install packaging==19.2
python -m pip install pluggy==0.13.1
python -m pip install protobuf==3.11.0
python -m pip install py==1.8.0
python -m pip install pyparsing==2.4.5
python -m pip install pyrsistent==0.15.6
python -m pip install pytest==5.3.1
python -m pip install python-engineio==3.10.0
python -m pip install python-socketio==4.4.0
python -m pip install PyYAML==5.1.2
python -m pip install ray==0.7.6
python -m pip install redis==3.3.11
python -m pip install scipy==1.3.3
python -m pip install six==1.13.0
python -m pip install wcwidth==0.1.7
python -m pip install Werkzeug==0.16.0
python -m pip install zipp==0.6.0
